### ISSUE TITLE
Published version of sembear does not work

### ISSUE THREAD

**Issue by Noviny** [mitchellhamilton/sembear#1]
[in the cjs.s file](https://unpkg.com/browse/sembear@0.4.0/dist/sembear.cjs.js) it just contains the word 'undefined', so exports an empty object.

This blocked installing manypkg in a project

Running `yarn preconstruct build` output:

```
'use strict';

if (process.env.NODE_ENV === "production") {
  module.exports = require("./sembear.cjs.prod.js");
} else {
  module.exports = require("./sembear.cjs.dev.js");
}
```

so I suspect build and republish should solve this.

**Comment by emmatown** [comment]
Published a new version that's fixed
